alertmanager:
  url: http://alertmanager.example.com
concourse:
  url: https://concourse.example.com
ledStrips:
  top:
    name: CI
    redPin: "GPIO27"
    greenPin: "GPIO17"
    bluePin: "GPIO22"
  bottom:
    name: Alerts
    redPin: "GPIO5"
    greenPin: "GPIO6"
    bluePin: "GPIO13"   
colors:
  normal:
    red: 0
    green: 132
    blue: 202
  warning:
    red: 239
    green: 1125
    blue: 0
  error:
    red: 197
    green: 40
    blue: 61
