alertmanager:
  url: http://alertmanager.example.com
concourse:
  url: https://concourse.example.com
callInterval: 10
ledStrips:
  top:
    name: CI
    redPin: "13"
    greenPin: "11"
    bluePin: "15"
  bottom:
    name: Alerts
    redPin: "29"
    greenPin: "31"
    bluePin: "33"
colors:
  normal:
    red: 0
    green: 132
    blue: 202
  warning:
    red: 239
    green: 1125
    blue: 0
  error:
    red: 197
    green: 40
    blue: 61